routes/web.php
<?php

Auth::routes();

Route::get('/admin', 'ProveedorController@inicio' ) ;
// Route::get('/', 'PagesController@' ) ;

Route::post('/admin','ProveedorController@crear') ->name('proveedor.create');
Route::get('/editar/{id}','ProveedorController@editar')->name('proveedor.editar');

Route::put('/editar/{id}','ProveedorController@update')->name('proveedor.update');
Route::delete('eliminar/{id}','ProveedorController@eliminar')->name('proveedor.eliminar');

Route::resource('categorias', 'CategoriasController');


Route::get('fotos','PagesController@fotos')->name('foto');

Route::get('nosotros/{nombre?}','PagesController@nosotros')->name('nosotros');


//  Route::get('/', 'HomeController@index')->name('home');


// Route::get('password/reset','Auth\ForgotPassworController@showLinkRequestForm')
// ->name('password.request');

// Route::post('password/email','Auth\ForgotPassworController@sendResetLinkEmail')
// ->name('password.email');

// Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')
// ->name('password.reset');

// Route::post('password/reset','Auth\ResetPassworController@reset');


// Auth::routes();

app/Categorias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorias extends Model
{
    protected $fillable =[
        'genero','talla','color'
        ];
}

app/Nota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Nota extends Model
{
    
    
}

app/Proveedor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proveedor extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;

use App\Categorias;
use Illuminate\Http\Request;
use Session;

class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias  = Categorias::orderBy('id','Asc')->paginate(4);
       return view('categorias.index',compact('categorias'));
    // return view('categorias.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

  public function __construct(){

     $this->middleware('auth');

    }


    public function create()
    {
        return view('categorias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'genero' => 'required',
            'talla' => 'required',
            'color' => 'required',
            ]);
            Categorias::create($request->all());
            
            Session::flash('message','Categoria Creada Correctamente');
            return redirect()->route('categorias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categorias  $categorias
     * @return \Illuminate\Http\Response
     */
    public function show(Categorias $categorias)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categorias  $categorias
     * @return \Illuminate\Http\Response
     */
    public function edit(Categorias $categoria)
    {
        return view('categorias.edit',compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categorias  $categorias
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categorias $categoria)
    {
        $request->validate([
            'genero' => 'required',
            'talla' => 'required',
            'color' => 'required',
            ]);
         
         $categoria->update($request->all());
    
            Session::flash('message','Categoria  Actualizado Correctamente');
            return redirect()->route('categorias.index');
    }

    /** 
     * Remove the specified resource from storage.
     *
     * @param  \App\Categorias  $categorias
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categorias $categoria)
    {
        $categoria->delete();
        Session::flash('message','Categoria Borrado Correctamente');
            return redirect()->route('categorias.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
       // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        aaaaaaaaaaaaaaaaaaaaaaaaaaaa
        //return view('home');

        //holaaa
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App;

class PagesController extends Controller
{

 public function __construct()
    {
        $this->middleware('auth');
    }


    public function inicio(){
        $notas = App\Nota::all();
        
         return view('welcome',compact('notas'));
        //return view('welcome');

    }

    // public function login(){
    //     return view('login');

    // }

     public function fotos(){
            return view('fotos');

     }
    public function nosotros($nombre = null){
        $equipo = ['Ignacio','Juanito','Pedrito'];

    return view('nosotros',compact('equipo','nombre'));
    }
    public function noticias(){
        return view('blog');

    }

}

app/Http/Controllers/ProveedorController.php
<?php


namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App;


class ProveedorController extends Controller
{


    public function __construct(){
            $this->middleware('auth');


    }
    public function inicio(){
        $proveedores = App\Proveedor::all();
        
         return view('welcome',compact('proveedores'));
        
    }

    public function crear(Request $request){

     //   return $request->all();

        $request->validate([
            'id'=>'required',
            'nombre' => 'required',
            'direccion' =>  'required',
            'telefono' =>  'required'

        ]);

     $proveedor = new App\Proveedor;

     $proveedor->id = $request->id;
     $proveedor->NombreProv = $request->nombre;
     $proveedor->Direccion = $request->direccion;
     $proveedor->Telefono= $request->telefono;

     $proveedor->save();
     return back()->with('mensaje','Proveedor agregado !');
    }

    
    public function editar ($id){

            $proveedor = App\Proveedor::findOrFail($id);
            return view('proveedor.editar',compact('proveedor'));

    }

  public function update (Request $request,$id){

            $proveedorUpdate = App\Proveedor::findOrFail($id);
            $proveedorUpdate->id = $request->id;
            $proveedorUpdate->NombreProv = $request->nombre;
            $proveedorUpdate->Direccion = $request->direccion;
            $proveedorUpdate->Telefono = $request->telefono;
            $proveedorUpdate->Save();

            return back()->with('mensaje','Datos Actualizados');

    }

public function eliminar($id){

            $proveedorEliminar = App\Proveedor::findOrFail($id);
            $proveedorEliminar->delete();


            return back()->with('mensaje','Dato Eliminado');

}









}

resources/views/blog.blade.php
@extends('plantilla')
@section('seccion')
<h1>Blog</h1>
@endsection

resources/views/categorias/create.blade.php
@extends('categorias.layout')
@section('content')
<h1 class="text-center">Agregar Categorias </h1>
<hr>
<div class="container">


<form action="{{ route('categorias.store')}}" method="POST">
        @csrf

        <div class="row">
        
           <div class="col-md-12">
                <div class="form-group">
                    <strong> Genero:</strong>
            <input type="text" name="genero" class="form-control" placeholder=" Genero">
          </div>
          </div>
          <div class="col-md-12">
                <div class="form-group">
                        <strong> Talla</strong>
            <input type="text" name="talla"  class="form-control" placeholder="talla">
                </div>
           </div>
           <div class="col-md-12">
                <div class="form-group">
                        <strong> Color</strong>
            <input type="text" name="color" class="form-control"  placeholder="color">
             </div>
           </div>
          <div class="col-md-12 text-center" >
               <button type="submit" class="btn btn-primary">Enviar</button>
        
        </div>
        </div>    
      </form> 
    </div>

@endsection

resources/views/categorias/edit.blade.php
@extends('categorias.layout')
@section('content')
<h1 class="text-center">Agregar Categorias </h1>
<hr>
<div class="container">


<form action="{{route('categorias.update', $categoria->id)}}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
        
           <div class="col-md-12">
                <div class="form-group">
                    <strong> Genero:</strong>
            <input type="text" name="genero" value="{{$categoria->genero}}" class="form-control" placeholder=" Genero">
          </div>
          </div>
          <div class="col-md-12">
                <div class="form-group">
                        <strong> Talla</strong>
            <input type="text" name="talla" value="{{$categoria->talla}}" class="form-control" placeholder="talla">
                </div>
           </div>
           <div class="col-md-12">
                <div class="form-group">
                        <strong> Color</strong>
            <input type="text" name="color" value="{{$categoria->color}}" class="form-control"  placeholder="color">
             </div>
           </div>
          <div class="col-md-12 text-center" >
               <button type="submit" class="btn btn-primary">Enviar</button>
        
        </div>
        </div>    
      </form> 
    </div> 

@endsection

resources/views/categorias/index.blade.php
@extends('categorias.layout')
@section('content')
<h1 class="text-center">Categorias </h1>
<div class="container">
    <a class="btn btn-info mb-3" href="{{route('categorias.create')}}">Categorias </a>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">id</th>
        <th scope="col">Genero</th>
        <th scope="col">Talla</th>
        <th scope="col">Color</th>
        <th scope="col">Actualizar</th>
        <th scope="col">Eliminar</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($categorias as $cat)
            
       
      <tr>
        <th scope="row">{{$cat->id}}</th>
        <td>{{$cat->genero}}</td>
        <td>{{$cat->talla}}</td>
        <td>{{$cat->color}}</td>
        <td><a class="btn btn-info" href="{{route('categorias.edit',$cat->id)}}"><i class="far fa-edit"></i></a></td>
      <td>
        <form action="{{route('categorias.destroy',$cat->id)}}" method="POST">
          @csrf
        @method('DELETE')
        <button type="submit" class="btn-sm btn-danger mt-3"><i class="far fa-trash-alt"></i> </button>
      </form>
        </td>
      </tr>
      @endforeach
     
    </tbody>
  </table>
  {{ $categorias->links() }}
</div>

@endsection

resources/views/categorias/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/styles.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" integrity="sha384-i1LQnF23gykqWXg6jxC2ZbCbUMxyw5gLZY6UiUS98LYV5unm8GWmfkIS6jqJfb4E" crossorigin="anonymous">

    <title>Categorias</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-custom">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">links</a>
                    </li>
                  </ul>
                </div>
              </nav>
    @yield('content')

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/fotos.blade.php
@extends('plantilla')
@section('seccion')
<h1>Fotos</h1>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">BIENVENIDO ADMINISTRADOR</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                   Has iniciado sesion 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>@yield('title') - Dierse</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css" integrity="sha256-CNwnGWPO03a1kOlAsGaH5g8P3dFaqFqqGFV/1nkX5OU=" crossorigin="anonymous" />
    <!-- Custom styles for this template -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>

<body>

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Curso de Laravel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url('/usuarios') }}">Usuarios</a>
                </li>
            </ul>
        </div>
    </nav>
</header> 

<!-- Begin page content -->
<main role="main" class="container">
    <div class="row mt-3">
        <div class="col-8">
            @yield('content')
        </div>
        <div class="col-4">
            <p>&nbsp;</p>
        </div>
    </div>
</main>

<footer class="footer">
    <div class="container">
        <span class="text-muted">https://styde.net</span>
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- <title>{{ config('app.name', 'Laravel') }}</title> --}}
    <title> Admin</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{-- {{ config('app.name', 'Administración-DIERSE') }}  ///// --}}
                 Administración-DIERSE   
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                {{-- <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a> --}}
                                <a class="nav-link" href="{{ route('login') }}">Inicie Sesionnn</a>

                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cieerreee') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/nosotros.blade.php
@extends ('plantilla')

@section('seccion')
 <h1>Este es mi equipo</h1>

@foreach ($equipo as $item )

<a href="{{ route('nosotros', $item ) }}" class ="h4 text-danger">{{$item}}</a><br>
    
@endforeach
@if (!empty($nombre))
@switch($nombre)
    @case($nombre=='Ignacio')
    <h2>El nombre es {{$nombre }}:</h2>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
         Quod nam debitis non sunt qui dolor eligendi, mollitia delectus eum
          quam nulla accusamus ipsa, accusantium consequatur possimus, perspiciatis
           perferendis cupiditate nihil?</p>      

@break
    @case($nombre=='Juanito')
<h2>El nombre es {{$nombre }}:</h2>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
         Quod nam debitis non sunt qui dolor eligendi, mollitia delectus eum
          quam nulla accusamus ipsa, accusantium consequatur possimus, perspiciatis
           perferendis cupiditate nihil?</p>      
        @break
    @case($nombre=='Pedrito')
<h2>El nombre es {{$nombre }}:</h2>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
         Quod nam debitis non sunt qui dolor eligendi, mollitia delectus eum
          quam nulla accusamus ipsa, accusantium consequatur possimus, perspiciatis
           perferendis cupiditate nihil?</p>      
        @break        
@endswitch
@endif  
@endsection

resources/views/plantilla.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
      <div class="container">
    {{-- <a href=" {{ route('foto') }} " class="btn btn-primary">Fotos</a>
    <a href="{{ route('noticias') }}" class="btn btn-primary">Blog</a>
    <a href="{{ route('nosotros') }}" class="btn btn-primary">Nosotros</a> --}}

</div>
<div class="container">
    @yield('seccion')
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/proveedor/editar.blade.php
@extends('plantilla')
@section('seccion')

 <h1>Editar</h1>
  @if (session('mensaje'))
      <div class="alert alert-success">
          {{ session('mensaje') }}
      </div>
  @endif
  <form action="{{ route('proveedor.update', $proveedor->id) }}" method="POST">
    @method('PUT')
    @csrf

    @error('id')
        <div class="alert alert-danger">
            El id es obligatorio
        </div>
    @enderror

    @error('nombre')
        <div class="alert alert-danger">
            El nombre es obligatoria
        </div>
    @enderror
    <input type="number" name="id" placeholder="Id proveedor" class="form-control mb-2" 
    value="{{ $proveedor->id }}">

    <input type="text" name="nombre" placeholder="Nombre" class="form-control mb-2"
     value="{{ $proveedor->NombreProv }}">
    <input type="text" name="direccion" placeholder="Direccion" class="form-control mb-2" 
    value="{{ $proveedor->Direccion }}">
    <input type="text" name="telefono" placeholder="Direccion" class="form-control mb-2" 
    value="{{ $proveedor->Telefono }}">
    <button class="btn btn-warning btn-block" type="submit">Editar</button>
  </form>
@endsection